function charArray = beaufortCrypt(word,key,spaces)
%This function takes a word, a key, and a boolean and encodes it using the
%beaufort cipher. The encryption and decryption processes are exactly the
%same. If you want to separate it with spaces, put 1 for the spaces
%argument, and if not, put 0.

    %Initialize independent variables
    cipher = ['ABCDEFGHIJKLMNOPQRSTUVWXYZ';...
              'BCDEFGHIJKLMNOPQRSTUVWXYZA';...
              'CDEFGHIJKLMNOPQRSTUVWXYZAB';...
              'DEFGHIJKLMNOPQRSTUVWXYZABC';...
              'EFGHIJKLMNOPQRSTUVWXYZABCD';...
              'FGHIJKLMNOPQRSTUVWXYZABCDE';...
              'GHIJKLMNOPQRSTUVWXYZABCDEF';...
              'HIJKLMNOPQRSTUVWXYZABCDEFG';...
              'IJKLMNOPQRSTUVWXYZABCDEFGH';...
              'JKLMNOPQRSTUVWXYZABCDEFGHI';...
              'KLMNOPQRSTUVWXYZABCDEFGHIJ';...
              'LMNOPQRSTUVWXYZABCDEFGHIJK';...
              'MNOPQRSTUVWXYZABCDEFGHIJKL';...
              'NOPQRSTUVWXYZABCDEFGHIJKLM';...
              'OPQRSTUVWXYZABCDEFGHIJKLMN';...







end
